//QuickSSH
//Copyright (C) 2023 Jose Phillips (jose@hddlive.net)

//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//any later version.

//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "autocomplete.h"
#include "qssh.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>



struct HostInfo {
    char host[100];
    char hostname[100];
};


struct HostInfo* read_config_file(int *num_hosts) {
    
    FILE *file = fopen(getConfigpath(), "r");
    if (!file) {
        perror("Error opening file");
        exit(EXIT_FAILURE);
    }

    struct HostInfo *host_info = malloc(sizeof(struct HostInfo) * 700); 

    char line[100];
    int index = 0;

    while (fgets(line, sizeof(line), file) != NULL) {
        line[strcspn(line, "\n")] = 0;

        if (sscanf(line, "Host %49s", host_info[index].host) == 1) {
            index++;
        } else if (sscanf(line, "    HostName %49s", host_info[index - 1].hostname) == 1) {
        }
    }

    fclose(file);
    *num_hosts = index;

    return host_info;
}


void fish_completions() {
    // Perform completions with the best SHELL
    // Yes it is.
    char *fish_completions_path = "/.config/fish/completions/";
    char *fish_completions_file = "qssh.fish";
    const char *homepath = getenv("HOME");
    if (homepath == NULL) {
        printf("Unable to determine homepath\n");
    }
  char *full_path = (char *)malloc(strlen(homepath) + strlen(fish_completions_path) + 1);
  char *fish_config_path = (char *)malloc(strlen(full_path) + strlen(fish_completions_file) + 1);

    strcpy(full_path, homepath);
    strcat(full_path, fish_completions_path);
    strcpy(fish_config_path,full_path);
    strcat(fish_config_path,fish_completions_file);



if (access(full_path, F_OK) != -1) {
       
     int num_hosts;
     struct HostInfo *host_info = read_config_file(&num_hosts);
     FILE *file = fopen(fish_config_path, "w");
     fprintf(file,"# Autogenerated by qssh don't modify this file changes will be overwritten.\n\n");
     for (int i = 0; i < num_hosts; i++) {
        fprintf(file, "complete -c qssh -n '__fish_use_subcommand' -a '%s' -d '%s'\n",host_info[i].host,host_info[i].hostname);
        
    }
    free(host_info);
    fclose(file);

    }
    }


void makeAutocomplete () {
    /* Completions methods should be made depending of the shell used.
    trying to use PS or echo $$ will don't work. */
    fish_completions();
        
}